services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=blps'
      - 'POSTGRES_PASSWORD=12345'
      - 'POSTGRES_USER=12345'

    ports:
      - '5430:5432'
volumes:
  pgdata:
